// client/components/instructor/instructorCoursesList.vue
<template>
    <div v-if="show">
        <h3>Courses Taught by Selected Instructor</h3>

        <table class="table">
            <thead>
                <tr>
                    <th></th>
                    <th>Number</th>
                    <th>Title</th>
                    <th>Department</th>
                </tr>
            </thead>
            <tbody>
                <tr is="instructor-course-row" v-for="course in courses" :course="course"
                    :select-course-action="selectCourseAction" :selected-course-id="selectedCourseId"></tr>
            </tbody>
        </table>
    </div>
</template>
<style lang="less" rel="stylesheet/less">

</style>
<script lang="ts" src="./instructorCoursesList.vue.ts"></script>

// client/components/instructor/InstructorCoursesList.tsx
import * as React from 'react';
import {connect} from 'react-redux';
import {bindActionCreators} from 'redux';
import * as _ from 'lodash';
import * as instructorActions from '../../actions/instructorActions';
import InstructorCourseRow from './InstructorCourseRow';

interface State {
    instructor: any,
    visible: boolean
}

interface Props {
    instructor: any,
    actions: any,
    visible: boolean,
    selectedCourseId: number,
    onSelectClick: any
}

class InstructorCoursesList extends React.Component<Props, State> {
    constructor(props) {
        super(props);

        this.state = {
            instructor: _.assign({}, props.instructor),
            visible: props.visible
        };
    }
    
    render() {
        let instructor = this.props.instructor;
        let courses = (instructor && instructor.courses) ? instructor.courses : [];

        let style = this.props.visible ? {display: 'block'} : {display: 'none'};

        return (
            <div style={style}>
                <h3>Courses Taught by Selected Instructor</h3>

                <table className="table">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Number</th>
                            <th>Title</th>
                            <th>Department</th>
                        </tr>
                    </thead>
                    <tbody>
                        {courses.map(course =>
                            <InstructorCourseRow key={course.id} course={course}
                                                 selectedCourseId={this.props.selectedCourseId}
                                                 onSelectClick={() => this.props.onSelectClick(course.id)}
                            />
                        )}
                    </tbody>
                </table>
            </div>
        );
    }
}

(InstructorCoursesList as any).propTypes = {
    instructor: React.PropTypes.object.isRequired,
    actions: React.PropTypes.object.isRequired,
    visible: React.PropTypes.bool.isRequired,
    selectedCourseId: React.PropTypes.number.isRequired,
    onSelectClick: React.PropTypes.func.isRequired
};

function mapStateToProps(state) {
    return {
        instructor: _.cloneDeep(state.instructor.current)
    };
}

function mapDispatchToProps(dispatch) {
    return {
        actions: (bindActionCreators as any)(instructorActions, dispatch)
    };
}

export default connect(mapStateToProps, mapDispatchToProps)(InstructorCoursesList);
