// client/components/instructor/InstructorDetails.tsx
import * as React from 'react';
import {connect} from 'react-redux';
import {Modal, Button} from 'react-bootstrap';
import * as _ from 'lodash';
import DisplayRow from '../common/DisplayRow';
import dateFormatter from '../../formatters/dateFormatter';

interface State {
    instructor: any,
    visible: boolean,
    close(): void
}

interface Props {
    instructor: any,
    visible: boolean,
    close(): void
}

class InstructorDetails extends React.Component<Props, State> {
    constructor(props) {
        super(props);

        this.state = {
            instructor: _.assign({}, props.instructor),
            visible: props.visible,
            close: props.close
        };
    }

    render() {
        let instructor = this.props.instructor;

        let office = instructor.officeAssignment;
        let location = office ? office.location : 'No office';
        let hireDate = dateFormatter.date(instructor.hireDate);

        return (
            <div>
                <Modal show={this.props.visible} onHide={this.props.close}>
                    <Modal.Header closeButton onClick={this.props.close}>
                        <Modal.Title>Instructor Details</Modal.Title>
                    </Modal.Header>
                    <Modal.Body>
                        <div className="form-horizontal">
                            <DisplayRow label="Office Location" value={location} />

                            <DisplayRow label="Last Name" value={instructor.lastName} />

                            <DisplayRow label="First Name" value={instructor.firstName} />

                            <DisplayRow label="Hire Date" value={hireDate} />
                        </div>
                    </Modal.Body>
                    <Modal.Footer>
                        <Button onClick={this.props.close}>Close</Button>
                    </Modal.Footer>
                </Modal>
            </div>
        );
    }
}

(InstructorDetails as any).propTypes = {
    instructor: React.PropTypes.object.isRequired,
    visible: React.PropTypes.bool.isRequired,
    close: React.PropTypes.func.isRequired
};

function mapStateToProps(state) {
    return {
        instructor: _.cloneDeep(state.instructor.current)
    };
}

export default connect(mapStateToProps)(InstructorDetails);

// client/components/instructor/instructorDetails.vue
<template>
    <modal :show.sync="show">
        <div slot="modal-header" class="modal-header">
            <h4 class="modal-title">Instructor Details</h4>
        </div>
        <div slot="modal-body" class="modal-body">
            <div class="form-horizontal">
                <display-row :label="'Office Location'" :value="location"></display-row>
                <display-row :label="'Last Name'" :value="instructor.lastName"></display-row>
                <display-row :label="'First Name'" :value="instructor.firstName"></display-row>
                <display-row :label="'Hire Date'" :value="hireDate"></display-row>
            </div>
        </div>
        <div slot="modal-footer" class="modal-footer">
            <button type="button" @click="cancel" class="btn btn-default">Close</button>
        </div>
    </modal>
</template>
<style lang="less" rel="stylesheet/less">

</style>
<script lang="ts" src="./instructorDetails.vue.ts"></script>
