// client/components/student/StudentDetails.tsx
import * as React from 'react';
import {connect} from 'react-redux';
import {Modal, Button} from 'react-bootstrap';
import * as _ from 'lodash';
import dateFormatter from '../../formatters/dateFormatter';
import StudentEnrollmentsList from './StudentEnrollmentsList';
import DisplayRow from '../common/DisplayRow';

interface State {
    student: any,
    visible: boolean,
    close(): void
}

interface Props {
    student: any,
    visible: boolean,
    close(): void
}

class StudentDetails extends React.Component<Props, State> {
    constructor(props) {
        super(props);

        this.state = {
            student: _.assign({}, props.student),
            visible: props.visible,
            close: props.close
        };
    }

    render() {
        let student = this.props.student;

        let enrollmentDate = dateFormatter.date(student.enrollmentDate);
        let enrollments = (student && student.enrollments) ? student.enrollments : [];
        let enrollmentsStyle = _.isEmpty(enrollments) ? {display: 'none'} : {};

        return (
            <div>
                <Modal show={this.props.visible} onHide={this.props.close}>
                    <Modal.Header closeButton onClick={this.props.close}>
                        <Modal.Title>Student Details</Modal.Title>
                    </Modal.Header>
                    <Modal.Body>
                        <div className="form-horizontal">
                            <DisplayRow label="Last Name" value={student.lastName} />

                            <DisplayRow label="First Name" value={student.firstName} />

                            <DisplayRow label="Enrollment Date" value={enrollmentDate} />
                            
                            <div className="form-group" style={enrollmentsStyle}>
                                <label className="col-xs-3 form-label">Enrollments:</label>
                                <div className="col-xs-9">
                                    <StudentEnrollmentsList enrollments={enrollments} />
                                </div>
                            </div>
                        </div>
                    </Modal.Body>
                    <Modal.Footer>
                        <Button onClick={this.props.close}>Close</Button>
                    </Modal.Footer>
                </Modal>
            </div>
        );
    }
}

(StudentDetails as any).propTypes = {
    student: React.PropTypes.object.isRequired,
    visible: React.PropTypes.bool.isRequired,
    close: React.PropTypes.func.isRequired
};

function mapStateToProps(state) {
    return {
        student: _.cloneDeep(state.student.current)
    };
}

export default connect(mapStateToProps)(StudentDetails);

// client/components/student/studentDetails.vue
<template>
    <modal :show.sync="show">
        <div slot="modal-header" class="modal-header">
            <h4 class="modal-title">Student Details</h4>
        </div>
        <div slot="modal-body" class="modal-body">
            <div class="form-horizontal">
                <display-row :label="'Last Name'" :value="student.lastName"></display-row>
                <display-row :label="'First Name'" :value="student.firstName"></display-row>
                <display-row :label="'Enrollment Date'" :value="enrollmentDate"></display-row>

                <div class="form-group">
                    <label class="col-xs-3 form-label">Enrollments:</label>
                    <div class="col-xs-9">
                        TODO
                    <!--    <StudentEnrollmentsList enrollments={enrollments} />-->
                    </div>
                </div>
            </div>
        </div>
        <div slot="modal-footer" class="modal-footer">
            <button type="button" @click="cancel" class="btn btn-default">Close</button>
        </div>
    </modal>
</template>
<style lang="less" rel="stylesheet/less">

</style>
<script lang="ts" src="./studentDetails.vue.ts"></script>
